services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webapp

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'

#  service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: service
#    restart: always
#    ports:
#      - "8083:8082"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webapp
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin